openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: A simple express product API
servers:
  - url: http://localhost:8000
paths:
  /:
    get:
      summary: Server information
      tags:
        - Product
      responses:
        '200':
          description: Server inofrmation
          content: null
  /api:
    get:
      summary: Get the production information
      tags:
        - Product
      responses:
        '200':
          description: Product inofrmaiton
components: {}
tags:
  - name: Product
    description: Product details
